<a href="https://colab.research.google.com/github/shivanshu5/python-practice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


In [ ]:
import numpy as np
arr = np.array([1,2,3,4])
arr


array([1, 2, 3, 4])

In [ ]:
a =[1,2,6.4,"raj"]
np.array(a)


array(['1', '2', '6.4', 'raj'], dtype='<U32')

Ther are difference of list & array one is vector and other is matrix
Vectors(List) : One dimension means only one row,
matrix (array):
one dimension & multiple dimension means mutiple  rows

In [ ]:
#list
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

generate ARRAY FUNCTIONS/METHODS






RANGE FUNCTION IN ARRAY

In [ ]:
np.arange(1,22,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

GENERATE ZEROS IN ARRAY

In [ ]:
np.zeros(6)
arr=np.zeros((4,7))
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [ ]:

arr=np.ones((4,7))
arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

linspace: return evely spaced numbers over a spacified interval

In [ ]:
arr = np.linspace(1,5,4)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

Random library to generate random numbers in array (this i vectors)
standrization : 0 to 1 normalization : -3 to 3

In [ ]:
#standarization
np.random.rand(10)


array([0.05950303, 0.9544898 , 0.826987  , 0.76250284, 0.20739209,
       0.63930014, 0.80745721, 0.86505481, 0.70824634, 0.8026522 ])

In [ ]:
#normalization
np.random.randn(10)

array([ 1.57009884e+00, -4.72917151e-04, -9.18748065e-01,  5.12396263e-02,
       -1.40309057e-02,  5.45169768e-01, -1.63692895e+00,  1.38903255e+00,
        1.62785359e-01, -7.70704980e-01])

In [ ]:
# generate in specific range
np.random.randint(10,20,5)

array([15, 17, 17, 16, 17])

ARRAT ATTRITUBES

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#size
arr.size

9

In [ ]:
#shape
arr.shape



(3, 3)

In [ ]:
#data type
arr.dtype

dtype('int64')

ARRAY METHOD

In [ ]:
#minimum
arr.min()

np.int64(1)

In [ ]:
#maximum
arr.max()

np.int64(9)

In [ ]:
#sum
arr.sum()

np.int64(45)

In [ ]:
#sum row and columns separately axis =1 for row and 0 for columns
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [ ]:
#mean
arr.mean()

np.float64(5.0)

In [ ]:
#standard deviation
arr.std()

np.float64(2.581988897471611)

In [ ]:
# arguments metrix index
arr.argmin()

np.int64(0)

Reshaping &  resizing


In [ ]:
#reshape
arr = np.arange(1,31
)
arr
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Slicing & indexing

In [ ]:
#Indexing
arr = np.arange(11,21)
arr[9]


np.int64(20)

In [ ]:
#SLicing
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

Numpy Indexing & Slicing of Matrix

In [ ]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[1] #this will show row indexing

array([ 6,  7,  8,  9, 10])

In [ ]:
# #this will show column indexing
arr[:,4]

array([ 5, 10, 15, 20, 25, 30])

In [ ]:
#slicing
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

BOOLEAN INDEXING

In [ ]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
#boolean indexing
bool_index = arr%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

array operations

In [ ]:
#arithmatic
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a1 + a2 #add
a1 - a2 #substract

a1 * a2 #multiply
a1 / a2 #division
a1 // a2 #floorDivision
a1 ** a2 #Exponential


array([      1,     128,    6561,  262144, 9765625])

In [ ]:
#Broadcasting
l = [20,20,30,40]
arr = np.array(l)
arr + 10

array([30, 30, 40, 50])

In [ ]:
# Deep & shallow copy
a = np.arange(1,21)
a
slice =a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [ ]:
a[4:6]*10

array([50, 60])

In [ ]:
#deep copy
a
b = a
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# make shallow copy of deep copy
a
b = a.copy()
b[0]=99
b

Matrix operation

In [ ]:
#Matrix multplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.dot(A,B)


array([[19, 22],
       [43, 50]])

In [ ]:
#Transpose  : row become column
A.T

array([[1, 3],
       [2, 4]])

Advanced array manipulation

In [ ]:
#Stacking of arrayor vectors to make matrix
#verticle stacking

np.vstack((A,B))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
#horizontal stack
np.hstack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
#column stack
np.column_stack((A,B))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
#Spliting array horizontally
c = np.arange(16).reshape(4,4)
c
np.hsplit(c,2)  #vsplit for verticle split


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
#Spliting array vertically
c = np.arange(16).reshape(4,4)
c
np.vsplit(c,2)